vich_uploader:
  db_driver: orm
    
#  metadata:
#    type:attribute


  mappings:
    post_thumbnail:
      uri_prefix: /fichier
      upload_destination: '%kernel.project_dir%/public/fichier'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
